permissions:
  contents: none # Minimal default permissions

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  all-jobs:
    if: always() # Otherwise this job is skipped if the matrix job fails
    name: all-jobs
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'

  test:
    name: test
    runs-on: ubuntu-latest
    permissions:
      contents: read # For actions/checkout@v4
    steps:
      - uses: actions/checkout@v4
      - run: cargo test
